// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: replicaconn.proto

package rpcserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WrappedMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       string                 `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrappedMsg) Reset() {
	*x = WrappedMsg{}
	mi := &file_replicaconn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrappedMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrappedMsg) ProtoMessage() {}

func (x *WrappedMsg) ProtoReflect() protoreflect.Message {
	mi := &file_replicaconn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrappedMsg.ProtoReflect.Descriptor instead.
func (*WrappedMsg) Descriptor() ([]byte, []int) {
	return file_replicaconn_proto_rawDescGZIP(), []int{0}
}

func (x *WrappedMsg) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *WrappedMsg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type NodePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardID       int64                  `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	NodeID        int64                  `protobuf:"varint,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePosition) Reset() {
	*x = NodePosition{}
	mi := &file_replicaconn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePosition) ProtoMessage() {}

func (x *NodePosition) ProtoReflect() protoreflect.Message {
	mi := &file_replicaconn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePosition.ProtoReflect.Descriptor instead.
func (*NodePosition) Descriptor() ([]byte, []int) {
	return file_replicaconn_proto_rawDescGZIP(), []int{1}
}

func (x *NodePosition) GetShardID() int64 {
	if x != nil {
		return x.ShardID
	}
	return 0
}

func (x *NodePosition) GetNodeID() int64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

type HandleMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           *WrappedMsg            `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	From          *NodePosition          `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *NodePosition          `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleMessageRequest) Reset() {
	*x = HandleMessageRequest{}
	mi := &file_replicaconn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleMessageRequest) ProtoMessage() {}

func (x *HandleMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replicaconn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleMessageRequest.ProtoReflect.Descriptor instead.
func (*HandleMessageRequest) Descriptor() ([]byte, []int) {
	return file_replicaconn_proto_rawDescGZIP(), []int{2}
}

func (x *HandleMessageRequest) GetMsg() *WrappedMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *HandleMessageRequest) GetFrom() *NodePosition {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *HandleMessageRequest) GetTo() *NodePosition {
	if x != nil {
		return x.To
	}
	return nil
}

type HandleMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleMessageResponse) Reset() {
	*x = HandleMessageResponse{}
	mi := &file_replicaconn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleMessageResponse) ProtoMessage() {}

func (x *HandleMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replicaconn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleMessageResponse.ProtoReflect.Descriptor instead.
func (*HandleMessageResponse) Descriptor() ([]byte, []int) {
	return file_replicaconn_proto_rawDescGZIP(), []int{3}
}

func (x *HandleMessageResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_replicaconn_proto protoreflect.FileDescriptor

const file_replicaconn_proto_rawDesc = "" +
	"\n" +
	"\x11replicaconn.proto\"@\n" +
	"\n" +
	"WrappedMsg\x12\x18\n" +
	"\amsgType\x18\x01 \x01(\tR\amsgType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"@\n" +
	"\fNodePosition\x12\x18\n" +
	"\ashardID\x18\x01 \x01(\x03R\ashardID\x12\x16\n" +
	"\x06nodeID\x18\x02 \x01(\x03R\x06nodeID\"w\n" +
	"\x14HandleMessageRequest\x12\x1d\n" +
	"\x03msg\x18\x01 \x01(\v2\v.WrappedMsgR\x03msg\x12!\n" +
	"\x04from\x18\x02 \x01(\v2\r.NodePositionR\x04from\x12\x1d\n" +
	"\x02to\x18\x03 \x01(\v2\r.NodePositionR\x02to\")\n" +
	"\x15HandleMessageResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack2M\n" +
	"\vReplicaConn\x12>\n" +
	"\rHandleMessage\x12\x15.HandleMessageRequest\x1a\x16.HandleMessageResponseB\rZ\v.;rpcserverb\x06proto3"

var (
	file_replicaconn_proto_rawDescOnce sync.Once
	file_replicaconn_proto_rawDescData []byte
)

func file_replicaconn_proto_rawDescGZIP() []byte {
	file_replicaconn_proto_rawDescOnce.Do(func() {
		file_replicaconn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replicaconn_proto_rawDesc), len(file_replicaconn_proto_rawDesc)))
	})
	return file_replicaconn_proto_rawDescData
}

var file_replicaconn_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_replicaconn_proto_goTypes = []any{
	(*WrappedMsg)(nil),            // 0: WrappedMsg
	(*NodePosition)(nil),          // 1: NodePosition
	(*HandleMessageRequest)(nil),  // 2: HandleMessageRequest
	(*HandleMessageResponse)(nil), // 3: HandleMessageResponse
}
var file_replicaconn_proto_depIdxs = []int32{
	0, // 0: HandleMessageRequest.msg:type_name -> WrappedMsg
	1, // 1: HandleMessageRequest.from:type_name -> NodePosition
	1, // 2: HandleMessageRequest.to:type_name -> NodePosition
	2, // 3: ReplicaConn.HandleMessage:input_type -> HandleMessageRequest
	3, // 4: ReplicaConn.HandleMessage:output_type -> HandleMessageResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_replicaconn_proto_init() }
func file_replicaconn_proto_init() {
	if File_replicaconn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replicaconn_proto_rawDesc), len(file_replicaconn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replicaconn_proto_goTypes,
		DependencyIndexes: file_replicaconn_proto_depIdxs,
		MessageInfos:      file_replicaconn_proto_msgTypes,
	}.Build()
	File_replicaconn_proto = out.File
	file_replicaconn_proto_goTypes = nil
	file_replicaconn_proto_depIdxs = nil
}
