// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: replicaconn.proto

package rpcserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplicaConn_HandleMessage_FullMethodName = "/ReplicaConn/HandleMessage"
)

// ReplicaConnClient is the client API for ReplicaConn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicaConnClient interface {
	HandleMessage(ctx context.Context, in *HandleMessageRequest, opts ...grpc.CallOption) (*HandleMessageResponse, error)
}

type replicaConnClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicaConnClient(cc grpc.ClientConnInterface) ReplicaConnClient {
	return &replicaConnClient{cc}
}

func (c *replicaConnClient) HandleMessage(ctx context.Context, in *HandleMessageRequest, opts ...grpc.CallOption) (*HandleMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleMessageResponse)
	err := c.cc.Invoke(ctx, ReplicaConn_HandleMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicaConnServer is the server API for ReplicaConn service.
// All implementations must embed UnimplementedReplicaConnServer
// for forward compatibility.
type ReplicaConnServer interface {
	HandleMessage(context.Context, *HandleMessageRequest) (*HandleMessageResponse, error)
	mustEmbedUnimplementedReplicaConnServer()
}

// UnimplementedReplicaConnServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicaConnServer struct{}

func (UnimplementedReplicaConnServer) HandleMessage(context.Context, *HandleMessageRequest) (*HandleMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleMessage not implemented")
}
func (UnimplementedReplicaConnServer) mustEmbedUnimplementedReplicaConnServer() {}
func (UnimplementedReplicaConnServer) testEmbeddedByValue()                     {}

// UnsafeReplicaConnServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicaConnServer will
// result in compilation errors.
type UnsafeReplicaConnServer interface {
	mustEmbedUnimplementedReplicaConnServer()
}

func RegisterReplicaConnServer(s grpc.ServiceRegistrar, srv ReplicaConnServer) {
	// If the following call pancis, it indicates UnimplementedReplicaConnServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplicaConn_ServiceDesc, srv)
}

func _ReplicaConn_HandleMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaConnServer).HandleMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicaConn_HandleMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaConnServer).HandleMessage(ctx, req.(*HandleMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicaConn_ServiceDesc is the grpc.ServiceDesc for ReplicaConn service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicaConn_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReplicaConn",
	HandlerType: (*ReplicaConnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleMessage",
			Handler:    _ReplicaConn_HandleMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "replicaconn.proto",
}
