name: PR Merge and Delete Branch

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  merge-and-delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh-cli@v1
        with:
          version: '2.7.0'

      - name: Merge PR with squash and delete branch
        if: github.event.pull_request.merged == true
        run: |
          PR_BRANCH=${{ github.head_ref }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Merging PR #${PR_NUMBER} with squash and deleting branch $PR_BRANCH"
          
          gh pr merge $PR_NUMBER --squash --delete-branch --confirm
